name: Process New Image

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**.jpg'

jobs:
  process-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ""

      - name: Get new image file path
        id: get_file
        run: |
          FILE_PATH=$(git diff-tree --no-commit-id --name-only -r HEAD | grep "images/")
          echo "::set-output name=filepath::$FILE_PATH"

      - name: Process image and update JSON
        run: |
          FILE_PATH="${{ steps.get_file.outputs.filepath }}"
          FILENAME=$(basename "$FILE_PATH")
          
          # Extract info from filename: {id}_{owner}_{tags}.jpg
          ID=$(echo "$FILENAME" | cut -d'_' -f1)
          OWNER=$(echo "$FILENAME" | cut -d'_' -f2)
          TAGS_STRING=$(echo "$FILENAME" | cut -d'_' -f3 | sed 's/\.jpg//')
          
          # Rename the file
          NEW_FILE_PATH="images/${ID}.jpg"
          git mv "$FILE_PATH" "$NEW_FILE_PATH"

          # Update data.json
          JSON_FILE="data.json"
          INDEX=$(jq length "$JSON_FILE")
          IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/${NEW_FILE_PATH}"
          
          jq \
            --argjson index "$INDEX" \
            --arg owner "$OWNER" \
            --arg tags "$TAGS_STRING" \
            --arg id "$ID" \
            --arg url "$IMAGE_URL" \
            '. += [{index: $index, owner: $owner, Tags: ($tags | split(",")), id: $id, Url: $url}]' \
            "$JSON_FILE" > tmp.json && mv tmp.json "$JSON_FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add images/ data.json
          git commit -m "Processed image ${ID}.jpg"
          git push
